updated get_list_of_unique_responses function
Analyticsphere/flatteningRequests pull request #41
Opened 2023-10-20 20:11 UTC by rebexxxxxx

hi jake-- this is the update for the get_list_of_unique_responses function, allowing the function to take in a column of variables, not just 1 and using DISTINCT within the SQL query. i will address the other changes that are involved with this vector input in the next pull request.

2023-10-20 20:19 UTC, jacobmpeters reviewed
This looks good to me! Were you able to test it?

To test it, ensure that the output is identical regardless of whether the new function or the old function is used. Then make sure the notebook still runs.

Because this change will brake the function that calls it, I'll wait until you complete the other item before merging this. I think that your next push will automatically be added to this PR.

Let me know if you have questions.

2023-10-25 19:26 UTC, rebexxxxxx commented
hi jake-- in this latest update, i further optimized the unique_responses() function to identify all unique responses from a vector of variables using 1 sql query. i also cleaned up the filter_vars_from_schema() function, removing a loop that called the unique_responses() function.

2023-10-25 19:42 UTC, jacobmpeters requested changes
Hi @rebexxxxxx , 

Thank you for writing such clean code and for testing it.

I'm just requesting a couple quick changes here related to the unnecessary arguments in the filter_vars_from_schema function. See related comment. 

Let me know if you have any questions!

2023-10-25 19:42 UTC, jacobmpeters commented on gcp_query_tools/connect_analytics_helper_functions.R
> -      }
Glad to see this inefficient loop go!

2023-10-25 19:42 UTC, jacobmpeters commented on gcp_query_tools/connect_analytics_helper_functions.R
> +        '{array_var}' AS variable,  # Label the array variable
This is an interesting way to construct the query in a loop. I'm not sure I understand it to be honest, but I know you've tested it. I might have you explain this to me sometime!

2023-10-25 19:42 UTC, jacobmpeters commented on gcp_query_tools/connect_analytics_helper_functions.R
>                                      output_file_type = "json"
I have a few suggestions here:
- [ ] rename GUV_out_json to out_json and remove the redundant argument
- [ ] remove the output_file_type argument now that we no longer need optional file types of "json" or "js"

2023-10-25 20:16 UTC, merged